### ISSUE TITLE
Implement deserialization for generated Plaf TOML and fixed column CSV

### ISSUE THREAD

**Issue by valeryz** [clvv/rcc#1]
Implement deserialization for generated Plaf TOML and fixed column CSV

Links to context:

https://github.com/Dhole/polyexen/blob/master/src/plaf/backends/halo2.rs#L158
Wei Dai4:43 PM
https://github.com/Dhole/polyexen/blob/master/src/plaf/backends/halo2.rs#L158
Wei Dai4:47 PM
https://github.com/clvv/rcc/blob/main/rcc/src/arithmetic_logic.rs
Wei Dai4:50 PM
https://github.com/clvv/rcc/tree/main/rcc-halo2
https://github.com/clvv/rcc/blob/main/rcc-halo2/src/composer.rs#L228

**Comment by clvv** [comment]
Closing for now since I've serde derive to most Plaf structs to a fork of Polyexen here: https://github.com/clvv/polyexen
